"""Initial schema: users, meals, ingredients, recipes, inventory

Revision ID: 2332ec0fb571
Revises: 
Create Date: 2026-02-05 18:17:16.210132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2332ec0fb571'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('calories_per_100g', sa.Integer(), nullable=False),
    sa.Column('carbs_per_100g', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('protein_per_100g', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fat_per_100g', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fiber_per_100g', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sugar_per_100g', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sodium_per_100g', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('usda_fdc_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usda_fdc_id')
    )
    op.create_index(op.f('ix_ingredients_category'), 'ingredients', ['category'], unique=False)
    op.create_index(op.f('ix_ingredients_name'), 'ingredients', ['name'], unique=False)
    op.create_table('recipes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cuisine_type', sa.String(length=50), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('prep_time_minutes', sa.Integer(), nullable=False),
    sa.Column('cook_time_minutes', sa.Integer(), nullable=False),
    sa.Column('servings', sa.Integer(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('carbs_g', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('protein_g', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fat_g', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=True),
    sa.Column('ai_prompt', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_difficulty'), 'recipes', ['difficulty'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('activity_level', sa.String(length=20), nullable=False),
    sa.Column('bmr_kcal', sa.Integer(), nullable=False),
    sa.Column('tdee_kcal', sa.Integer(), nullable=False),
    sa.Column('target_calories', sa.Integer(), nullable=False),
    sa.Column('target_carbs_g', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('target_protein_g', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('target_fat_g', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('goal_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('inventory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('amount_g', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('low_stock_threshold', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_expiry_date'), 'inventory', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_inventory_user_id'), 'inventory', ['user_id'], unique=False)
    op.create_table('meals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=False),
    sa.Column('food_name', sa.String(length=255), nullable=False),
    sa.Column('amount_g', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('carbs_g', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('protein_g', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fat_g', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fiber_g', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sugar_g', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sodium_mg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meals_consumed_at'), 'meals', ['consumed_at'], unique=False)
    op.create_index(op.f('ix_meals_user_id'), 'meals', ['user_id'], unique=False)
    op.create_table('nutrition_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_calories', sa.Integer(), nullable=False),
    sa.Column('total_carbs_g', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_protein_g', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_fat_g', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('remaining_calories', sa.Integer(), nullable=False),
    sa.Column('remaining_carbs_g', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('remaining_protein_g', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('remaining_fat_g', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('goal_achievement_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrition_history_user_id'), 'nutrition_history', ['user_id'], unique=False)
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('amount_g', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('is_optional', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_ingredients_ingredient_id'), 'recipe_ingredients', ['ingredient_id'], unique=False)
    op.create_index(op.f('ix_recipe_ingredients_recipe_id'), 'recipe_ingredients', ['recipe_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipe_ingredients_recipe_id'), table_name='recipe_ingredients')
    op.drop_index(op.f('ix_recipe_ingredients_ingredient_id'), table_name='recipe_ingredients')
    op.drop_table('recipe_ingredients')
    op.drop_index(op.f('ix_nutrition_history_user_id'), table_name='nutrition_history')
    op.drop_table('nutrition_history')
    op.drop_index(op.f('ix_meals_user_id'), table_name='meals')
    op.drop_index(op.f('ix_meals_consumed_at'), table_name='meals')
    op.drop_table('meals')
    op.drop_index(op.f('ix_inventory_user_id'), table_name='inventory')
    op.drop_index(op.f('ix_inventory_expiry_date'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_recipes_difficulty'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_ingredients_name'), table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_category'), table_name='ingredients')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
